/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef LISTAFILAED_PRIVATE_H
#define LISTAFILAED_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"FIPP"
#define FILE_VERSION	"1.0.0.0"
#define FILE_DESCRIPTION	"FIPP"
#define INTERNAL_NAME	"FIPP"
#define LEGAL_COPYRIGHT	"FIPP"
#define LEGAL_TRADEMARKS	"FIPP"
#define ORIGINAL_FILENAME	"FIPP"
#define PRODUCT_NAME	"FIPP"
#define PRODUCT_VERSION	"1.0.0.0"

#endif /*LISTAFILAED_PRIVATE_H*/
