# Project: listaFilaED
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = ../ArquivosParaGerarOExecutavel/listaFilaED_private.res
OBJ      = ../ArquivosParaGerarOExecutavel/main.o $(RES)
LINKOBJ  = ../ArquivosParaGerarOExecutavel/main.o $(RES)
LIBS     = -L"C:/Dev-Cpp/MinGW64/lib32" -L"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lconio -m32
INCS     = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ../listaFilaED.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../ArquivosParaGerarOExecutavel/main.o: ../main.cpp
	$(CPP) -c ../main.cpp -o ../ArquivosParaGerarOExecutavel/main.o $(CXXFLAGS)

../ArquivosParaGerarOExecutavel/listaFilaED_private.res: listaFilaED_private.rc 
	$(WINDRES) -i listaFilaED_private.rc -F pe-i386 --input-format=rc -o ../ArquivosParaGerarOExecutavel/listaFilaED_private.res -O coff 

